### ISSUE TITLE
How to solve this `Bad state: Stream has already been listened to`.

### ISSUE THREAD

**Issue by posawatji** [ben-xD/push#18] opened 2023-07-03 12:29 UTC
flutter verion 3.7.12
push version 1.0.0

When I sign out and remove my homepage, then sign in again, it goes back to my homepage and shows an error message below.

``` bash
Bad state: Stream has already been listened to.
```

### Code follows the example
ref. https://github.com/ben-xD/push/blob/main/push/example/lib/main.dart#L113C16-L113C16
``` dart
    useEffect(() {
      final onBackgroundMessageSubscription =
          Push.instance.onBackgroundMessage.listen((message) {
              //  TODO: implement some tasks.
          });

      return () {
        onBackgroundMessageSubscription.cancel(); // NOTE: I think the onBackgroundMessageSubscription does not cancel when my home page had dispose.
      };
    }, []);

```

please share a solution to handle it.

**Comment by ben-xD** [comment] 2023-07-22 04:47
Hey @posawatji, sorry for the late response.

I initially thought you could convert the stream to a broadcast stream:
```dart
      final onBackgroundMessageSubscription = Push.instance.onBackgroundMessage
          .asBroadcastStream()
          .listen((message) {
        print('RemoteMessage received while app is in background:\n'
            'RemoteMessage.Notification: ${message.notification} \n'
            ' title: ${message.notification?.title.toString()}\n'
            ' body: ${message.notification?.body.toString()}\n'
            'RemoteMessage.Data: ${message.data}');
        backgroundMessagesReceived.value += [message];
      });
```

But the second call would error with `Stream has already been listened to.`, even if you cancelled the first.

**Suggested fix:** I'd need to create the broadcast stream in `push` so users don't create multiple broadcast streams. _What do you think?_

**Comment by JosephNK0608** [comment] 2023-08-05 12:13
```
_onNotificationTap = push.Push.instance.onNotificationTap.listen((data) async {});
_onNotificationTap.cancel();
```
can i do this?

**Comment by RudolfVonKrugstein** [comment] 2023-08-29 20:13
This issue also occurs during integration tests.
Whay would be nice (for this usecase) is, if one could reset the Push.instance so that the app can start again and the streams are re-created.

**Comment by ObranS** [comment] 2023-10-02 09:50
Same issue still reproduces on 1.0.5

**Comment by ben-xD** [comment] 2023-12-29 11:33
Hey @ObranS, @RudolfVonKrugstein, @Raphael929 and @posawatji,

I've made a change to the API that fixes this issue. See https://github.com/ben-xD/push/pull/43
>  you can try: 2.0.0-dev.1

**Comment by ben-xD** [comment] 2024-01-22 07:40
Closing since this should be solved :)

**Closed by ben-xD** 2024-01-22 07:40 UTC
Labels: enhancement

**Comment by PiotrWpl** [comment] 2024-04-25 11:52
@ben-xD #43 fixed issues for messages and background messages, but not for `onNewToken` and `onNotificationTap`. Any plans to expand the fix also for these two?

**Comment by bull-xu** [comment] 2024-05-28 04:35
We had the same issue on onNewToken or onNotificationTap, the main widget to have the useEffect was composed inside a FutureBuilder.

Our solution is to use useMemoized to keep the future value.

**Comment by iffanmajid** [comment] 2024-11-07 11:11
> We had the same issue on onNewToken or onNotificationTap, the main widget to have the useEffect was composed inside a FutureBuilder.
> 
> Our solution is to use useMemoized to keep the future value.

Yes i had this issue. Any workaround solution for StatefulWidget?
